### PR TITLE
Fixed build.processing not being refreshed and never completes

### PR DESCRIPTION
**Pull request by jp-cen**
Hey @KrauseFx 

I discovered a bug in the pull request you merged from me. My builds never wait for processing because I submit a batch of 150 before selecting the build so I missed it in my testing. Basically it seems that calling build.processing doesn't re-retrieve the build object from ITC therefore processing is not refreshed, so it will never change to true. The fix basically re-retrieves and finds the same build based on the upload_date and then checks the status from there

### CODE REVIEW

**Comment by KrauseFx** [comment]
```ruby

    def wait_for_build
      raise "Could not find app with app identiifer #{WatchBuild.config[:app_identifier]}".red unless app

      loop do
        build = find_build
        return build if build.processing == false

        Helper.log.info "Waiting iTunes Connect processing for build #{build.train_version} (#{build.build_version})... this might take a while..."
        sleep 30
      end
      nil
    end
```

```ruby
    def find_build
      build = nil
      app.latest_version.candidate_builds.each do |b|
        if !build or b.upload_date > build.upload_date
          build = b
        end
      end

      unless build
        Helper.log.fatal v.candidate_builds
        raise "Could not find build".red
      end

      return build
    end
```

That's how I'd solve it, what do you think @PeterCen?

**Comment by PeterCen** [comment]
Great, @KrauseFx ! I've added changed the code based your suggestion. I tested it for selecting a build when there's a processed build and when there's no build. I still need to test it for selecting a build that's in processing.

**Comment by KrauseFx** [comment]
Thanks, please let me know once you tested it so I can push a new release :+1:

**Comment by PeterCen** [comment]
Tested it on a bunch of builds last night and it works

**Comment by KrauseFx** [comment]
:+1:

**Pull request merged**
