### PR TITLE
[Feature] Considering "Redundant Binary Upload" error as a success

### PR DESCRIPTION
**Pull request by dral3x**
This is optional, of course.
Declaring `ENV['DELIVER_IGNORE_REDUNDANT_BINARY_UPLOAD_ERROR']="true"` will let `deliver` handle this issue as a success, when it happens.

### CODE REVIEW

**Comment by dral3x** [comment]
@KrauseFx do you think this will be merge into master some day? Just asking

**Comment by KrauseFx** [comment]
Sorry @dral3x, somehow missed that pull request. As you probably know I'm working on a big refactor of `deliver`, which also includes moving the transporter into `fastlane_core`: https://github.com/fastlane/fastlane_core/blob/master/lib/fastlane_core/itunes_transporter.rb

Could you describe what's the exact error you'd get and how this should be handled differently and I can implement this in the new version of `deliver` :+1: 

I'll close the pull request for now.

**Comment by dral3x** [comment]
Makes sense to me! :+1: 

If the error message returned by transporter contains "Redundant Binary Upload." that means the same ipa file is already be uploaded and there is no need to upload it again. The full error message is like this `ERROR ITMS-9000: "Redundant Binary Upload. There already exists a binary upload with build version '1.0' for train '1.0'"`

So, if we define the boolean flag `ENV['DELIVER_IGNORE_REDUNDANT_BINARY_UPLOAD_ERROR']` to true, we can consider that specific error a success and move along.

**Comment by KrauseFx** [comment]
Shouldn't this even be default maybe? So that the user doesn't have to set this environment variable.

**Comment by dral3x** [comment]
Good point. Probably it should be ON by default

Il martedì 15 settembre 2015, Felix Krause <notifications@github.com> ha
scritto:

> Shouldn't this even be default maybe? So that the user doesn't have to set
> this environment variable.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KrauseFx/deliver/pull/284#issuecomment-140534402>.
>


-- 
Alessandro Calzavara
http://about.me/alessandro.calzavara

**Comment by KrauseFx** [comment]
Thanks :+1:

**Pull request closed without merging**
