### PR TITLE
[FEATURE] Add ability to upload optional primary first and second sub-categories

### PR DESCRIPTION
**Pull request by MarcL**
This pull request adds the ability to update the primary first and second sub categories as discussed in issue #393. I've tested it locally and it seems to work fine by adding a `primary_first_sub_category.txt` and `primary_second_sub_category.txt` to the `metdata` folder.

I've chosen to **only** implement this for the primary category even though [spaceship](https://github.com/fastlane/spaceship) appears to support secondary first and second sub-categories too. This is due to the fact that iTunes Connect returns an error if both the primary and secondary categories are set to `Games` as you cannot set a duplicate category. As `deliver` currently does not validate the categories, I thought it might be confusing for the user to implement both. I'm happy to implement them if needed.

### CODE REVIEW

**Comment by lacostej** [comment]
Hei Marc, I was working on the same feature.

I did the following: https://github.com/lacostej/deliver/commit/a17d63100e39f9d68ea3e779c018458463a4e609

Very similar, except that I support both primary and secondary, as well as updated the migration guide.

**Comment by lacostej** [comment]
BTW, on my project, Game is secondary_category, hence my need of having support for both.

**Comment by KrauseFx** [comment]
Thanks for taking the time to prepare the pull request @MarcL. This is merged with https://github.com/KrauseFx/deliver/pull/398 and I'll push a new version in a few minutes :+1:

**Comment by MarcL** [comment]
@lacostej - I wasn't sure whether to add secondary first/second too but I guess it makes more sense to be complete. I just noticed that I uploaded my metadata for primary and secondary to `Games` the other night and iTunes Connect gave an error.

Perhaps it might be worth adding some validation against the known categories so that it avoids trying to pushing the metadata if it's invalid?

No problems @KrauseFx. This has been my first pull request to an open source project so I'm glad I could help. Thanks for making some really useful software! :+1:

**Comment by KrauseFx** [comment]
@MarcL :smiley: 

I decided to not do any validation in `spaceship` itself, since Apple's categories might change, so we don't have to update `spaceship` every time that happens.

**Comment by MarcL** [comment]
@KrauseFx Yes, fair point.

**Pull request closed without merging**
