### PR TITLE
[Ready] deliver upgrade to spaceship

### PR DESCRIPTION
**Pull request by KrauseFx**
Upgrade to the new [spaceship](https://spaceship.airforce) and with it fix all the iTunes Connect front-end issues.

Open points:

Important:
- [x] Re-Implement `spaceship` parts to use the new iTC
- [x] Update to the new screenshot concept
- [x] Implement submission to the App Store
- [x] App Icon und Watch Icon upload
- [x] Set Price Tier
- [x] Automatically set the build after it was uploaded
- [x] Set copyright
- [x] Set categories
- [x] Set app review information
- [x] Prefer framed screenshots over plain screenshots (for `frameit`)
- [x] `automatic_release` option is not yet implemented
- [x] Create a new language
- [x] HTML summary should display both new data and existing one
- [x] Automatically create a new version (need `spaceship` update)
- [x] Setting the app age rating is not possible
- [x] `submit_further_information` is not yet implemented
- [x] Set the app's age rating
- [x] Update `fastlane` action
- [x] Update documentation
- [x] Migration Guide to 1.0

### CODE REVIEW

**Comment by KrauseFx** [comment]
The tests are all failing as this pull request requires the latest feature version of [spaceship](https://github.com/fastlane/spaceship)

**Comment by tobiasstrebitzer** [comment]
Any idea on when this will be ready? Also let me know if I can help in any way

**Comment by KrauseFx** [comment]
@tobiasstrebitzer thanks, I'd love some help with the new `spaceship`, you can follow the progress over [here](https://github.com/fastlane/spaceship/pull/58). I'll send you more information on where you could help :+1:

**Comment by KrauseFx** [comment]
New Release https://github.com/KrauseFx/deliver/releases/tag/1.0.0.beta3

**Comment by KrauseFx** [comment]
All open tasks are now moved to https://github.com/KrauseFx/deliver/issues/353

**Pull request merged**
