### PR TITLE
Only wait for latest build to process instead of all

### PR DESCRIPTION
**Pull request by jp-cen**
I have two apps that have a previous build that has been stuck in "Processing" hell since they were uploaded a month ago. Since we're only selecting the latest build, we can just check whether the lastest one has finished processing.

### CODE REVIEW

**Comment by KrauseFx** [comment]
That makes sense. Sorry for not taking a look at this earlier. Could you update the pull request so that we don't have merge conflicts? 

Have you tested the fix for your setup?

**Comment by KrauseFx** [comment]
Thanks :+1:

**Comment by PeterCen** [comment]
No problem! Sorry it took a while and yes I've used this branch to push about 120 app updates in the last month.

**Comment by KrauseFx** [comment]
That's great, thanks @PeterCen :+1:

**Comment by PeterCen** [comment]
@KrauseFx, found a bug in this, check my latest commit/pull request

**Pull request merged**
